<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.fundaciobit.pluginsib.validatesignature</groupId>
    <artifactId>pluginsib-validatesignature</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <artifactId>
            caib-artifacts-github-governib-distribution-with-jdk11-jboss72</artifactId>
        <groupId>es.caib.maven</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <name>PluginsIB - Validate Signature</name>

    <properties>
        <afirma.version>1.6.5</afirma.version>
        <validatecertificate.version>3.0.0-SNAPSHOT</validatecertificate.version>
    </properties>

    <modules>
        <module>api</module>
        <module>fake</module>
        <module>afirmacxf</module>
        <module>validatesignaturetester</module>
    </modules>

    <developers>
        <developer>
            <id>anadal-fundaciobit</id>
            <name>Antoni Nadal</name>
        </developer>
    </developers>

    <organization>
        <name>Fundació Bit - Govern Digital</name>
        <url>https://governdigital.fundaciobit.org</url>
    </organization>

    <licenses>
        <license>
            <name>European Union Public Licence (EUPL v1.2)</name>
            <url>
                https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_es.pdf</url>
        </license>
    </licenses>

    <repositories>
        <repository>
            <id>github_governib_maven</id>
            <name>GitHub GovernIB Maven Repository</name>
            <url>https://governib.github.io/maven/maven/</url>
        </repository>
    </repositories>


    <dependencies>
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.core.v3</groupId>
            <artifactId>pluginsib-core</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.core.v3</groupId>
            <artifactId>pluginsib-core</artifactId>
            <version>3.0.0-SNAPSHOT</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Definició dels plugins estàndar de maven -->
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.0.0-M1</version>
                </plugin>

                <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>

                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                </plugin>
                <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.0.0-M5</version>
                </plugin>

                <plugin>
                    <artifactId>maven-ejb-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-ear-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.0.0-M1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.9.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>

        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Profile per executar els tests d'integració -->
            <id>testsIntegracio</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
